
lpc-base-tiles/*.png: &lpc-base
    derived-from: lpc-base-tiles

-nilsson-lpc: &nilsson-lpc
    derived-from: nilsson-lpc-entry

gervais_roguelike/*.png: &gervais-roguelike
    derived-from: gervais-roguelike-tiles

daneeklu_farming_tilesets/*.png: &daneeklu-farming
    derived-from: daneeklu-farming-tilesets


lpc-dirt2-cross.png: *lpc-base
lpc-cave-walls2.png: *lpc-base
lpc-watergrass-cross.png: *lpc-base
lpc-cave-top-cross.png: *lpc-base
lpc-cave-top.png: *lpc-base
lpc-cave-inside.png: *lpc-base


# Based on the witch hat sprite sheet
equip_hat_icon.png: &witch-hat
    attribution: Based on the witch hat sprite sheet
equip_hat_icon_remove.png: *witch-hat

party-hat-icon.*:
    title: Party Hat
    author: Stuart Pernsteiner

key32.png:
    derived-from: williamson-roguelike-items

candle32.png:
    title: Candle Icon
    author: Stuart Pernsteiner

farmland-interior-parts.png:
    title: LPC Farmland - Interior Tiles
    author: Stuart Pernsteiner
    attribution: >
        The plowed soil tiles from daneeklu's farming tileset, with major
        edits to produce a set of 16x16 subtiles for building interior region
        tiles.
    derived-from: daneeklu-farming-tilesets

outdoor-ramps.png:
    title: LPC Outdoor Ramps
    author: Anonymous
    derived-from: lpc-base-tiles

