tilesetformattedupdate1.png: &16x16-indoor-rpg
    title: "16x16 indoor rpg tileset: the baseline"
    author: Stephen Challener (Redshrike)
    license: CC-BY 3.0 / OGA-BY 3.0
    url: http://opengameart.org/content/16x16-indoor-rpg-tileset-the-baseline
    attribution:
        Art by Stephen Challener (Redshrike). Commissioned by OpenGameArt.org
        (http://opengameart.org)
16x16extratiles_0.PNG: *16x16-indoor-rpg

"rpg indoor tileset expansion 1 trans.png":
    title: "RPG Indoor Tileset: Expansion 1"
    author: Redshrike
    license: CC-BY 3.0 / OGA-BY 3.0
    url: http://opengameart.org/content/rpg-indoor-tileset-expansion-1
    attribution:
        Stephen Challener (Redshrike) and Jetrel, hosted by OpenGameArt.org

Castle_2.png: &castle-tiles
    title: Castle Tiles for RPG's
    author: Hyptosis, Zabin, Daniel Cook
    license: CC-BY 3.0
    url: http://opengameart.org/content/castle-tiles-for-rpgs
    attribution:
        Zabin, Hyptosis, and Danial Cook and a link back to www.OpenGameart.org
Castle2.png: *castle-tiles
CastleExample_4.png: *castle-tiles

PathAndObjects_0.png:
    title: "RPG Tiles: Cobble stone paths & town objects"
    author: Zabin, Daneeklu, Jetrel, Hyptosis, Redshrike, Bertram
    license: CC-BY-SA 3.0
    url: http://opengameart.org/content/rpg-tiles-cobble-stone-paths-town-objects
    attribution: >
        Credit goes to: Zabin, Daneeklu, Jetrel, Hyptosis, Redshrike, Bertram.
        A link back to this page
        "http://opengameart.org/content/rpg-tiles-cobble-stone-paths-town-objects
        to see who did what"

hyptosis_sprites-and-tiles-for-you.png: &hyptosis-pack
    title: Lots of free 2d tiles and sprites by Hyptosis
    author: Hyptosis
    license: CC-BY 3.0
    url: http://opengameart.org/content/lots-of-free-2d-tiles-and-sprites-by-hyptosis
    attribution:
        Please credit Hyptosis and Zabin (only drew 6 frames of the bomb's
        wick burning) from OGA and respect to the License.
hyptosis_tile-art-batch-1.png: *hyptosis-pack
hyptosis_til-art-batch-2.png: *hyptosis-pack
hyptosis_tile-art-batch-3.png: *hyptosis-pack
hyptosis_tile-art-batch-4.png: *hyptosis-pack
hyptosis_tile-art-batch-5.png: *hyptosis-pack

mountain_landscape_23.png:
    title: 2d Lost Garden Zelda style tiles resized to 32x32 with additions
    author: Daniel Cook, Jetrel, Saphy (TMW), Zabin, Bertram
    license: CC-BY 3.0
    url: http://opengameart.org/content/2d-lost-garden-zelda-style-tiles-resized-to-32x32-with-additions
    attribution:
        Credit goes to Daniel Cook's 2d Circle Graphic Archive, Jetrel's
        mockups resized 32x32, Bertram's improvements, Zabin's modification
        and additions, Saphy (TMW) tall grass and please provide a link
        back to OGA and this submission.

tilesetformattedupdate1_0.png:
    title: 16x16 JRPG tilesets enlarged 2x
    author: multiple artists
    license: CC-BY 3.0
    url: http://opengameart.org/content/16x16-jrpg-tilesets-enlarged-2x
    attribution:
        Cave, desert, sewer, and overworld sets by MrBeast. Interior tileset by
        RedShrike. Town tiles by Surt, modified by Blarumyrran. Snow town tiles
        are a modification of the town tileset by Sharm. Forest tiles contained
        in the town set are by Sharm. Some of these works were commissioned by
        OpenGameArt.org (http://opengameart.org).

wood_tileset_3.png:
    title: 2d lost Garden tileset transition to Jetrel's Wood tileset
    author: Jetrel, Daniel Cook, Zabin
    license: CC-BY-SA 3.0
    url: http://opengameart.org/content/2d-lost-garden-tileset-transition-to-jetrels-wood-tileset
    attribution:
        Credit goes to Jetrel, Daniel Cook, Bertram and Zabin


"lpc-base-tiles/*.png":
    title: Liberated Pixel Cup (LPC) Base Assets (sprites & map tiles)
    author:
        Lanea Zimmerman (AKA Sharm),
        Stephen Challener (AKA Redshrike),
        Charles Sanchez (AKA CharlesGabriel),
        Manuel Riecke (AKA MrBeast),
        Daniel Armstrong (AKA HughSpectrum)
    license: CC-BY-SA 3.0 / GPL 3.0
    url: http://opengameart.org/content/liberated-pixel-cup-lpc-base-assets-sprites-map-tiles
    attribution: |
        Lanea Zimmerman (AKA Sharm)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~

        Base tileset
         - barrel.png
         - brackish.png
         - buckets.png
         - bridges.png
         - cabinets.png
         - cement.png
         - cementstair.png
         - chests.png
         - country.png
         - cup.png
         - dirt2.png
         - dirt.png
         - dungeon.png
         - grassalt.png
         - grass.png
         - holek.png
         - holemid.png
         - hole.png
         - house.png
         - inside.png
         - kitchen.png
         - lava.png
         - lavarock.png
         - mountains.png
         - rock.png
         - shadow.png
         - signs.png
         - stairs.png
         - treetop.png
         - trunk.png
         - waterfall.png
         - watergrass.png
         - water.png
         - princess.png and princess.xcf

        Much style guide work

        co-author of LPC background cup image

        Stephen Challener (AKA Redshrike)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

        Character templates
         - female_walkcycle.png
         - female_hurt.png
         - female_slash.png
         - female_spellcast.png
         - male_walkcycle.png
         - male_hurt.png
         - male_slash.png
         - male_spellcast.png
         - male_pants.png
         - male_hurt_pants.png
         - male_fall_down_pants.png
         - male_slash_pants.png

        Much style guide work


        Charles Sanchez (AKA CharlesGabriel)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

        Monsters
         - bat.png
         - bee.png
         - big_worm.png
         - eyeball.png
         - ghost.png
         - man_eater_flower.png
         - pumpking.png
         - slime.png
         - small_worm.png
         - snake.png

        Manuel Riecke (AKA MrBeast)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~

         - hairfemale.png and hairfemale.xcf
         - hairmale.png and hairmale.xcf
         - soldier.png
         - soldier_altcolor.png

        The 60 degree perspective render in the style guide


        Daniel Armstrong (AKA HughSpectrum)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

        Castle work:

         - castlewalls.png
         - castlefloors.png
         - castle_outside.png
         - castlefloors_outside.png
         - castle_lightsources.png

terrain_atlas.png: &lpc-tile-sheet-1
    title: LPC Tile Atlas
    author:
        Lanea Zimmerman (AKA Sharm),
        Stephen Challener (AKA Redshrike),
        Charles Sanchez (AKA CharlesGabriel),
        Manuel Riecke (AKA MrBeast),
        Daniel Armstrong (AKA HughSpectrum),
        Casper Nilsson,
        Daniel Eddeland,
        Johann CHARLOT,
        Skyler Robert Colladay 
    license: CC-BY-SA 3.0 / GPL 3.0
    url: http://opengameart.org/content/lpc-tile-atlas
    attribution: |
        License 
        -------

        CC-BY-SA 3.0:
         - http://creativecommons.org/licenses/by-sa/3.0/
         - See the file: cc-by-sa-3.0.txt
        GNU GPL 3.0:
         - http://www.gnu.org/licenses/gpl-3.0.html
         - See the file: gpl-3.0.txt

        Note the file is based on the LCP contest readme so don't expect the exact little pieces used like the base one.
        *Additional license information.

        Assets from:

        LPC participants:
        ----------------

        Casper Nilsson
            *GNU GPL 3.0 or later
            email: casper.nilsson@gmail.com
            Freenode: CasperN
            OpenGameArt.org: C.Nilsson
            
         - LPC C.Nilsson (2D art)

        Daniel Eddeland 
            *GNU GPL 3.0 or later
         - Tilesets of plants, props, food and environments, suitable for farming / fishing sims and other games. 
         - Includes wheat, grass, sand tilesets, fence tilesets and plants such as corn and tomato. 

        Johann CHARLOT 
            *GNU LGPL Version 3. 
            *Later versions are permitted.
            Homepage  http://poufpoufproduction.fr
            Email     johannc@poufpoufproduction.fr
            
         - Shoot'em up graphic kit

        Skyler Robert Colladay 

         - FeralFantom's Entry (2D art)

        BASE assets:
        ------------

        (see "LPC Base Assets" listing)
    derived-from: "lpc-base-tiles/*.png"

lpc-trees-unscaled.png: &rescaled-trees
    title: LPC Trees (edited)
    author: Lanea Zimmerman (AKA Sharm), Casper Nilsson, Stuart Pernsteiner
    license: CC-BY-SA 3.0 / GPL 3.0
    attribution:
        Lanea Zimmerman's tree trunks and Casper Nilsson's tree stump, copied
        from the LPC Tile Atlas and edited slightly (including 4x rescaling
        using xBRZ).

        According to the readme from the .zip file at
        http://opengameart.org/content/lpc-cnilsson,
        C.Nilsson's art is CC-BY-SA 3.0 / GPL 3+ dual licensed (not GPL3+ only,
        as the LPC Tile Atlas license section suggests).
    derived-from: terrain_atlas.png
lpc-trees-unscaled.xcf: *rescaled-trees
lpc-trees-scaled.png: *rescaled-trees


lpc-house.png: &house-walls
    title: LPC House Walls
    author: Lanea Zimmerman (AKA Sharm), Stuart Pernsteiner
    license: CC-BY-SA 3.0 / GPL 3.0
    attribution:
        Lanea Zimmerman's house interior and exterior tiles, edited together to
        form a solid 64px-tall wall.
    derived-from: "lpc-base-tiles/*.png"
lpc-house.xcf: *house-walls

lpc-wood-floor.png: &wood-floor
    title: LPC Wood Floor
    author: Lanea Zimmerman (AKA Sharm), Stuart Pernsteiner
    license: CC-BY-SA 3.0 / GPL 3.0
    attribution:
        Lanea Zimmerman's wood floor tile, rearranged to match the standard
        terrain layout.
    derived-from: "lpc-base-tiles/inside.png"
lpc-wood-floor.xcf: *wood-floor

lpc-furniture.png: &furniture
    title: LPC Furniture
    author: Lanea Zimmerman (AKA Sharm), Stuart Pernsteiner
    license: CC-BY-SA 3.0 / GPL 3.0
    attribution:
        Lanea Zimmerman's LPC house furniture, rearranged to line up with the
        modified house walls.
    derived-from: "lpc-base-tiles/cabinets.png"
lpc-furniture.xcf: *furniture

lpc-watergrass-cross.png: &watergrass-cross
    title: LPC Water/Grass Diagonal Crossing
    author: Lanea Zimmerman (AKA Sharm), Stuart Pernsteiner
    license: CC-BY-SA 3.0 / GPL 3.0
    attribution:
        Lanea Zimmerman's water/grass border, edited to make "diagonal
        crossing" variants.
    derived-from: "lpc-base-tiles/watergrass.png"
lpc-watergrass-cross.xcf: *watergrass-cross

lpc-cave-walls.png: &cave-walls
    title: LPC Cave Walls
    author: Lanea Zimmerman (AKA Sharm), Stuart Pernsteiner
    license: CC-BY-SA 3.0 / GPL 3.0
    attribution:
        Lanea Zimmerman's mountainside tiles, edited to form a solid 64px-tall
        cave wall.
    derived-from: "lpc-base-tiles/mountain.png"
lpc-cave-walls.xcf: *cave-walls

lpc-cave-top.png: *cave-walls
lpc-cave-top-cross.png: *cave-walls

lpc-cave-inside.png:
    title: LPC Cave Interior
    author: Lanea Zimmerman (AKA Sharm), Stuart Pernsteiner
    license: CC-BY-SA 3.0 / GPL 3.0
    attribution:
        Cave wall rearranged and cut up to form interior walls.
    derived-from: lpc-cave-walls.png

"daneeklu_farming_tilesets/*.png":
    title: "[LPC] Farming tilesets, magic animations and UI elements"
    author: Daniel Eddeland (daneeklu)
    license: CC-BY-SA 3.0 / GPL 3.0
    url: http://opengameart.org/content/lpc-farming-tilesets-magic-animations-and-ui-elements
    attribution:
        Please attribute creator as Daniel Eddeland. Please include a link to
        opengameart.org as well (preferably to the submission for this art
        package) if you use the art. 

"gervais_roguelike/*":
    title: Roguelike Tiles (large collection)
    author: David E. Gervais
    license: CC-BY 3.0
    url: http://opengameart.org/content/roguelike-tiles-large-collection
    attribution: >
        Author's website: http://pousse.rapiere.free.fr/tome/

"crystal-ward.png": &crystal-ward
    title: Crystal Ward
    author: David E. Gervais, Daniel Eddeland, Stuart Pernsteiner
    license: CC-BY-SA 3.0
    attribution: >
        Fence post from Daniel Eddeland's LPC farming tileset, combined with an
        edited crystal from David E. Gervais's roguelike tilesets.
    derived-from: daneeklu_farming_tilesets/fence.png, gervais_roguelike/dg_misc32.gif
"crystal-ward.xcf": *crystal-ward

"crystal-formation.png":
    title: Blue Crystal Formation
    author: David E. Gervais
    license: CC-BY-SA 3.0
    derived-from: gervais_roguelike/dg_misc32.gif

nilsson_lpc_entry/Harbor/*.png:
    title: LPC C.Nilsson
    author: Casper Nilsson
    license: CC-BY-SA 3.0 / GPL 3.0
    url: http://opengameart.org/content/lpc-cnilsson
    attribution: >
        LICENSE
        ---------------------------------
        The art is dual licensed under the following licenses.
        *CC-BY-SA 3.0
        *GNU GPL 3.0 or later
         
        http://creativecommons.org/licenses/by-sa/3.0/
        http://www.gnu.org/licenses/gpl-3.0.html

        Please attribute creator as Casper Nilsson.
        Please include a link to opengameart.org as well (preferably to the submission for this art package) if you use the art.


equip_hat_icon.png:
    title: Witch's Hat (Icon)
    author: Fernando Ariel dos Santos Alves
    license: CC-BY 4.0

statue_icon.png:
    title: Pony Statue (Icon)
    author: Fernando Ariel dos Santos Alves
    license: CC-BY 4.0

cup_icon.png:
    title: LPC Trophy Icon
    author: Lanea Zimmerman (AKA Sharm)
    license: CC-BY-SA 3.0 / GPL 3.0
    attribution:
        Rescaled trophy from Lanea Zimmerman's LPC contributions
    derived-from: lpc-base-tiles/cup.png

fountain_icon.png:
    title: LPC Fountain Icon
    author: Lanea Zimmerman (AKA Sharm)
    license: CC-BY 3.0
    derived-from: ../structures/fountain.png
