"*.png":
    title: MLPonline Sprite Sheets
    author: urimas
    license: Custom
    url: http://urimas.deviantart.com/art/MLPonline-Sprite-Sheets-341840400
    attribution: >
        "There are no restrictions on how these are used as long as i'm
        credited. and linked back here"
    derived-from: >
        ../../maresprite.png
        ../../frontwingmare.png
        ../../backwingmare.png
        ../../marehorn.png
