structures/food_bag.png:
    title: "[LPC] Farming tilesets, magic animations and UI elements"
    author: Daniel Eddeland (daneeklu)
    license: CC-BY-SA 3.0 / GPL 3.0
    url: http://opengameart.org/content/lpc-farming-tilesets-magic-animations-and-ui-elements
    attribution:
        Please attribute creator as Daniel Eddeland. Please include a link to
        opengameart.org as well (preferably to the submission for this art
        package) if you use the art. 
